steps:
  - name: "nixos/nix"
    script: |
      echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      nix run .#container > image.tar
  - name: gcr.io/cloud-builders/docker
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    script: |
      docker load -i image.tar
      docker tag turtyboi/schemebot:latest europe-west3-docker.pkg.dev/$PROJECT_ID/main/schemebot:latest

      
images:
  - "europe-west3-docker.pkg.dev/$PROJECT_ID/main/schemebot:latest"

options:
  logging: CLOUD_LOGGING_ONLY
  
