name: Build and deploy for arm64
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: turtyboi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and load container
        run: |
          nix build .#container
          ./result | docker load
      - name: Push
        run: |
          docker tag turtyboi/schemebot:latest turtyboi/schemebot:latest-arm64
          docker push turtyboi/schemebot:latest-arm64
